package web

import (
	"context"
	"log"
	"net/http"
	"time"

	"github.com/EgorLis/my-docs/internal/config"
	_ "github.com/EgorLis/my-docs/internal/docs" // docs generated by Swag CLI
	"github.com/EgorLis/my-docs/internal/transport/web/mw"
	"github.com/EgorLis/my-docs/internal/transport/web/v1/health"
	//httpSwagger "github.com/swaggo/http-swagger"
)

type Server struct {
	log    *log.Logger
	server *http.Server
	cfg    *config.Config
}

func New(logger *log.Logger, cfg *config.Config, db health.DBPinger) *Server {
	healthLog := log.New(logger.Writer(), logger.Prefix()+"[health] ", logger.Flags())

	healthHandler := &health.Handler{DBPinger: db, Log: healthLog}

	srv := &http.Server{
		Addr:              cfg.AppPort,
		Handler:           newRouter(healthHandler, logger),
		ReadTimeout:       10 * time.Second,
		WriteTimeout:      10 * time.Second,
		MaxHeaderBytes:    1 << 20,
		ReadHeaderTimeout: 2 * time.Second,
		IdleTimeout:       60 * time.Second,
	}
	return &Server{server: srv, cfg: cfg, log: logger}
}

func (ws *Server) Run() {
	ws.log.Printf("started on %s", ws.server.Addr)
	if err := ws.server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		ws.log.Fatalf("error: %v", err)
	}
}

func (ws *Server) Close(ctx context.Context) {
	if err := ws.server.Shutdown(ctx); err != nil {
		ws.log.Printf("forced to shutdown: %v", err)
	}
	ws.log.Println("exited gracefully")
}

func newRouter(hh *health.Handler, logger *log.Logger) http.Handler {
	mux := http.NewServeMux()

	// health
	mux.HandleFunc("GET /v1/healthz", hh.Liveness)
	mux.HandleFunc("GET /v1/readyz", hh.Readiness)

	// swagger
	//mux.Handle("GET /swagger/", httpSwagger.WrapHandler)

	// 🔗 цепочка middleware: RequestID → Logging
	return mw.WithRequestID(mw.Logging(logger)(mux))
}

func limitBody(n int64, h http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		r.Body = http.MaxBytesReader(w, r.Body, n)
		h(w, r)
	}
}
